### ISSUE TITLE
Save Station

### ISSUE THREAD

**Issue by TuxNix** [smurfy/fahrplan#183] opened 2015-04-02 17:49 UTC
It would be nice, if this app could save some stations often used.

**Comment by TuxNix** [comment] 2015-04-02 17:54
I

**Comment by TuxNix** [comment] 2015-04-02 17:58
It would be nice, if this app could save some statons often used.

**Comment by leppa** [comment] 2015-04-02 19:19
Thank you for your suggestion. Sounds like a duplicate of #144. Is that something you suggest?

**Comment by TuxNix** [comment] 2015-04-02 19:40
Yes Leppa, it is the same idea.

**Comment by smurfy** [comment] 2015-04-03 07:07
Ok, so i close this, as duplicate :) 
But yea, such a feature would be great.

**Closed** 2015-04-03 07:06 UTC
Labels: Backend, Feature, Frontend
