### ISSUE TITLE
Add providers for Italy (Trenitalia, LeFrecce)

### ISSUE THREAD

**Issue by bittner** [smurfy/fahrplan#214] opened 2015-06-25 09:33 UTC
I'm using *fahrplan* on my Ubuntu Touch device, and I like it a lot. Italy is not covered yet, though.

Do you plan to add [Trenitalia](http://www.trenitalia.com/) or [LeFrecce.it](https://www.lefrecce.it/B2CWeb/search.do?parameter=searchAdvInputViewer&cFID=SGdxOkoQG5Z7)?

There is already a WebApp for Ubuntu Touch for Trenitalia, but an integrated experience with *fahrplan* would be nice.

**Comment by benna86** [comment] 2015-08-23 17:30
Duplicate of https://github.com/smurfy/fahrplan/issues/152

**Closed** 2015-08-23 19:37 UTC
